name: FullWorkflow-PR-backend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  docker_backend:
    uses: ./.github/workflows/docker.yml
    with:
      build_context: "backend"
