name: Release Workflow

on:
  workflow_call:
    outputs:
      a-release_created:
        value: ${{ jobs.release_job.outputs.a-release_created }}
      a-tag_name:
        value: ${{ jobs.release_job.outputs.a-tag_name }}
      frontend-release_created:
        value: ${{ jobs.release_job.outputs.frontend-release_created }}
      frontend-tag_name:
        value: ${{ jobs.release_job.outputs.frontend-tag_name }}

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

concurrency:
  group: release

jobs:
  release_job:
    runs-on: ubuntu-latest
    outputs:
      a-release_created: ${{ steps.create_output.outputs.a-release_created }}
      a-tag_name: ${{ steps.create_output.outputs.a-tag_name }}
      frontend-release_created: ${{ steps.create_output.outputs.frontend-release_created }}
      frontend-tag_name: ${{ steps.create_output.outputs.frontend-tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release with release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          monorepo-tags: true
          pull-request-header: ":robot: I have created a release"
      - name: "Generate release-please output"
        id: create_output
        shell: bash
        run: |
          echo "a-release_created=$(echo ${{ steps.release.outputs['model/a--release_created'] }})" >> "$GITHUB_OUTPUT"
          echo "a-tag_name=$(echo ${{ steps.release.outputs['model/a--tag_name'] }})" >> "$GITHUB_OUTPUT"
          echo "frontend-release_created=$(echo ${{ steps.release.outputs['frontend--release_created'] }})" >> "$GITHUB_OUTPUT"
          echo "frontend-tag_name=$(echo ${{ steps.release.outputs['frontend--tag_name'] }})" >> "$GITHUB_OUTPUT"
  build_publish_backend_image:
    name: Build Publish a Image
    uses: ./.github/workflows/docker.yml
    needs: release_job
    if: needs.release_job.outputs.a-release_created == 'true'
    with:
      image_tag: ${{ needs.release_job.outputs.a-tag_name }}
      build_context: "backend"
  build_publish_frontend_image:
    name: Build Publish a Image
    uses: ./.github/workflows/docker.yml
    needs: release_job
    if: needs.release_job.outputs.frontend-release_created == 'true'
    with:
      image_tag: ${{ needs.release_job.outputs.frontend-tag_name }}
      build_context: "frontend"

