name: FullWorkflow-Release-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
