name: FullWorkflow-Release-backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    needs: [style, tests_a, python_style_a]
    uses: ./.github/workflows/release.yaml
